import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import readline from 'node:readline/promises'
import process from 'node:process'

function defaultConfigDir() {
  if (process.platform === 'darwin') {
    return path.join(os.homedir(), 'Library', 'Application Support', 'IdleWatch')
  }
  return path.join(os.homedir(), '.config', 'idlewatch')
}

function ensureDir(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true })
}

function writeSecureFile(filePath, content) {
  ensureDir(path.dirname(filePath))
  fs.writeFileSync(filePath, content, { encoding: 'utf8', mode: 0o600 })
  try {
    fs.chmodSync(filePath, 0o600)
  } catch {
    // best effort on filesystems that ignore chmod
  }
}

function parseServiceAccountFile(filePath) {
  const raw = fs.readFileSync(filePath, 'utf8')
  const json = JSON.parse(raw)
  if (json.type !== 'service_account') {
    throw new Error('Credential file is not a service_account JSON key.')
  }
  if (!json.project_id) {
    throw new Error('Credential file is missing project_id.')
  }
  return { raw, json }
}

function promptModeText() {
  return `\nSelect enrollment mode:\n  1) Production Firestore (recommended)\n  2) Firestore emulator (local development)\n  3) Local-only (no Firebase writes)\n`
}

export async function runEnrollmentWizard(options = {}) {
  const nonInteractive = options.nonInteractive || process.env.IDLEWATCH_ENROLL_NON_INTERACTIVE === '1'
  const configDir = path.resolve(options.configDir || process.env.IDLEWATCH_ENROLL_CONFIG_DIR || defaultConfigDir())
  const outputEnvFile = path.resolve(options.outputEnvFile || process.env.IDLEWATCH_ENROLL_OUTPUT_ENV_FILE || path.join(configDir, 'idlewatch.env'))

  let mode = options.mode || process.env.IDLEWATCH_ENROLL_MODE || null
  let projectId = options.projectId || process.env.IDLEWATCH_ENROLL_PROJECT_ID || null
  let serviceAccountFile = options.serviceAccountFile || process.env.IDLEWATCH_ENROLL_SERVICE_ACCOUNT_FILE || null
  let emulatorHost = options.emulatorHost || process.env.IDLEWATCH_ENROLL_EMULATOR_HOST || '127.0.0.1:8080'

  let rl = null
  if (!nonInteractive) {
    rl = readline.createInterface({ input: process.stdin, output: process.stdout })
    console.log('IdleWatch enrollment wizard')
    console.log('This wizard stores an env file and (optional) least-privilege service-account file path.')
    console.log(promptModeText())
    const modeInput = (await rl.question('Mode [1/2/3] (default 1): ')).trim() || '1'
    mode = modeInput === '2' ? 'emulator' : modeInput === '3' ? 'local' : 'production'
  }

  if (!mode) mode = 'production'
  if (!['production', 'emulator', 'local'].includes(mode)) {
    throw new Error(`Invalid enrollment mode: ${mode}`)
  }

  if (mode !== 'local' && !projectId) {
    if (!rl) throw new Error('Missing project id (IDLEWATCH_ENROLL_PROJECT_ID).')
    projectId = (await rl.question('Firebase project id: ')).trim()
  }

  if ((mode === 'production') && !serviceAccountFile) {
    if (!rl) throw new Error('Missing service account file (IDLEWATCH_ENROLL_SERVICE_ACCOUNT_FILE).')
    console.log('\nLeast-privilege recommendation: create a dedicated service account used only by IdleWatch, with minimal Firestore write role scope.')
    serviceAccountFile = (await rl.question('Path to service-account JSON file: ')).trim()
  }

  if (mode === 'emulator' && !emulatorHost && rl) {
    emulatorHost = (await rl.question('Firestore emulator host [127.0.0.1:8080]: ')).trim() || '127.0.0.1:8080'
  }

  const envLines = [
    '# Generated by idlewatch-agent quickstart',
    'IDLEWATCH_OPENCLAW_USAGE=auto'
  ]

  if (mode === 'local') {
    envLines.push('# Local-only mode (no Firebase writes).')
  } else {
    envLines.push(`FIREBASE_PROJECT_ID=${projectId}`)
  }

  if (mode === 'emulator') {
    envLines.push(`FIRESTORE_EMULATOR_HOST=${emulatorHost}`)
  }

  if (mode === 'production') {
    const resolvedInput = path.resolve(serviceAccountFile)
    if (!fs.existsSync(resolvedInput)) {
      throw new Error(`Service account file not found: ${resolvedInput}`)
    }
    const parsed = parseServiceAccountFile(resolvedInput)
    if (projectId && parsed.json.project_id !== projectId) {
      throw new Error(
        `Service-account project_id (${parsed.json.project_id}) does not match FIREBASE_PROJECT_ID (${projectId}).`
      )
    }

    const credentialDir = path.join(configDir, 'credentials')
    ensureDir(credentialDir)
    const securedCopyPath = path.join(credentialDir, `${projectId || parsed.json.project_id}-service-account.json`)
    writeSecureFile(securedCopyPath, parsed.raw)
    envLines.push(`FIREBASE_SERVICE_ACCOUNT_FILE=${securedCopyPath}`)
    envLines.push('IDLEWATCH_REQUIRE_FIREBASE_WRITES=1')
  }

  writeSecureFile(outputEnvFile, `${envLines.join('\n')}\n`)

  if (rl) rl.close()

  return {
    mode,
    configDir,
    outputEnvFile,
    projectId: projectId || null
  }
}
