import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import readline from 'node:readline/promises'
import process from 'node:process'
import { spawnSync } from 'node:child_process'

function defaultConfigDir() {
  return path.join(os.homedir(), '.idlewatch')
}

function ensureDir(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true })
}

function writeSecureFile(filePath, content) {
  ensureDir(path.dirname(filePath))
  fs.writeFileSync(filePath, content, { encoding: 'utf8', mode: 0o600 })
  try {
    fs.chmodSync(filePath, 0o600)
  } catch {
    // best effort on filesystems that ignore chmod
  }
}

function parseServiceAccountFile(filePath) {
  const raw = fs.readFileSync(filePath, 'utf8')
  const json = JSON.parse(raw)
  if (json.type !== 'service_account') {
    throw new Error('Credential file is not a service_account JSON key.')
  }
  if (!json.project_id) {
    throw new Error('Credential file is missing project_id.')
  }
  return { raw, json }
}

const DEFAULT_MANAGED_PROJECT_ID = 'idlewatch-f2b23'

function tryRustTui({ configDir, outputEnvFile }) {
  const disabled = process.env.IDLEWATCH_DISABLE_RUST_TUI === '1'
  if (disabled) return false

  const cargoProbe = spawnSync('cargo', ['--version'], { stdio: 'ignore' })
  if (cargoProbe.status !== 0) return false

  const manifestPath = path.resolve(process.cwd(), 'tui', 'Cargo.toml')
  if (!fs.existsSync(manifestPath)) return false

  const run = spawnSync('cargo', ['run', '--quiet', '--manifest-path', manifestPath], {
    stdio: 'inherit',
    env: {
      ...process.env,
      IDLEWATCH_ENROLL_CONFIG_DIR: configDir,
      IDLEWATCH_ENROLL_OUTPUT_ENV_FILE: outputEnvFile
    }
  })

  if (run.status === 0) {
    return true
  }

  return false
}

function promptModeText() {
  return `\n╭───────────────────────────────────────────────╮\n│              IdleWatch Setup Wizard           │\n╰───────────────────────────────────────────────╯\n\nChoose setup mode:\n  1) Managed cloud (recommended)\n     Uses default project and secure local key storage\n  2) Local-only (no cloud writes)\n`
}

export async function runEnrollmentWizard(options = {}) {
  const nonInteractive = options.nonInteractive || process.env.IDLEWATCH_ENROLL_NON_INTERACTIVE === '1'
  const configDir = path.resolve(options.configDir || process.env.IDLEWATCH_ENROLL_CONFIG_DIR || defaultConfigDir())
  const outputEnvFile = path.resolve(options.outputEnvFile || process.env.IDLEWATCH_ENROLL_OUTPUT_ENV_FILE || path.join(configDir, 'idlewatch.env'))

  let mode = options.mode || process.env.IDLEWATCH_ENROLL_MODE || null
  let projectId = options.projectId || process.env.IDLEWATCH_ENROLL_PROJECT_ID || DEFAULT_MANAGED_PROJECT_ID
  let serviceAccountFile = options.serviceAccountFile || process.env.IDLEWATCH_ENROLL_SERVICE_ACCOUNT_FILE || null
  let cloudApiKey = options.cloudApiKey || process.env.IDLEWATCH_CLOUD_API_KEY || null
  let cloudIngestUrl = options.cloudIngestUrl || process.env.IDLEWATCH_CLOUD_INGEST_URL || 'https://idlewatch.com/api/ingest'
  let emulatorHost = options.emulatorHost || process.env.IDLEWATCH_ENROLL_EMULATOR_HOST || '127.0.0.1:8080'

  if (!nonInteractive && tryRustTui({ configDir, outputEnvFile })) {
    return {
      mode: 'tui',
      configDir,
      outputEnvFile,
      projectId: DEFAULT_MANAGED_PROJECT_ID
    }
  }

  let rl = null
  if (!nonInteractive) {
    rl = readline.createInterface({ input: process.stdin, output: process.stdout })
    console.log(promptModeText())
    console.log(`Storage path: ${configDir}`)
    console.log(`Environment file: ${outputEnvFile}`)
    const modeInput = (await rl.question('\nMode [1/2] (default 1): ')).trim() || '1'
    mode = modeInput === '2' ? 'local' : 'production'
  }

  if (!mode) mode = 'production'
  if (!['production', 'emulator', 'local'].includes(mode)) {
    throw new Error(`Invalid enrollment mode: ${mode}`)
  }

  if (mode !== 'local' && !projectId) {
    if (!rl) throw new Error('Missing project id (IDLEWATCH_ENROLL_PROJECT_ID).')
    projectId = DEFAULT_MANAGED_PROJECT_ID
  }

  if ((mode === 'production') && !cloudApiKey) {
    if (!rl) throw new Error('Missing cloud API key (IDLEWATCH_CLOUD_API_KEY).')
    console.log('\nPaste the API key from idlewatch.com/dashboard.')
    cloudApiKey = (await rl.question('Cloud API key: ')).trim()
  }

  if (mode === 'emulator' && !emulatorHost && rl) {
    emulatorHost = (await rl.question('Firestore emulator host [127.0.0.1:8080]: ')).trim() || '127.0.0.1:8080'
  }

  const localLogPath = path.join(configDir, 'logs', `${os.hostname().replace(/[^a-zA-Z0-9_.-]/g, '_')}-metrics.ndjson`)
  const localCachePath = path.join(configDir, 'cache', `${os.hostname().replace(/[^a-zA-Z0-9_.-]/g, '_')}-openclaw-last-good.json`)

  const envLines = [
    '# Generated by idlewatch-agent quickstart',
    'IDLEWATCH_OPENCLAW_USAGE=auto',
    `IDLEWATCH_LOCAL_LOG_PATH=${localLogPath}`,
    `IDLEWATCH_OPENCLAW_LAST_GOOD_CACHE_PATH=${localCachePath}`
  ]

  if (mode === 'local') {
    envLines.push('# Local-only mode (no cloud/Firebase writes).')
  }

  if (mode === 'emulator') {
    envLines.push(`FIRESTORE_EMULATOR_HOST=${emulatorHost}`)
  }

  if (mode === 'production') {
    if (!cloudApiKey) {
      throw new Error('Cloud API key is required for production mode.')
    }
    envLines.push(`IDLEWATCH_CLOUD_INGEST_URL=${cloudIngestUrl}`)
    envLines.push(`IDLEWATCH_CLOUD_API_KEY=${cloudApiKey}`)
    envLines.push('IDLEWATCH_REQUIRE_CLOUD_WRITES=1')
  }

  writeSecureFile(outputEnvFile, `${envLines.join('\n')}\n`)

  if (rl) rl.close()

  return {
    mode,
    configDir,
    outputEnvFile,
    projectId: projectId || null
  }
}
